project:
  type: website
  output-dir: docs

website:
  title: "MortezaML"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/smhajimirzaei
      - icon: linkedin
        href: https://www.linkedin.com/in/s-morteza-h-mirzaei/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

